DROP DATABASE IF EXISTS coffeeshopDB;
CREATE DATABASE coffeeshopDB;
USE coffeeshopDB;


CREATE TABLE CUSTOMER
(
    `customerID` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `email` CHAR(255) NOT NULL,
    `password` VARCHAR(20) NOT NULL,
    `fname` VARCHAR(255) NOT NULL,
    `lname` VARCHAR (255) NOT NULL,
    `phoneNr` CHAR(11) NOT NULL
);

CREATE TABLE PRODUCT
(
    `productID` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `description` VARCHAR (255) NOT NULL,
    `price` INT NOT NULL,
    `stock` INT NOT NULL,
    `origin` VARCHAR (255) NOT NULL,
    `type` VARCHAR (255) NOT NULL,
    `isSpecial` BOOLEAN NULL
);

CREATE TABLE POSTALCODE 
(
    `postalCode` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `city` VARCHAR(255) NOT NULL
);

CREATE TABLE ADRESS 
(
    postalCode INT NOT NULL,
    `adressID` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    FOREIGN KEY (postalCode) REFERENCES POSTALCODE(postalCode)
);

CREATE TABLE `ORDER`
(
    `orderID` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    customerID INT NOT NULL,
    adressID INT NOT NULL,
    `date` DATETIME NOT NULL,
    FOREIGN KEY (customerID) REFERENCES CUSTOMER (customerID),
    FOREIGN KEY (adressID) REFERENCES ADRESS (adressID)
);

CREATE TABLE `ORDERHASPRODUCT`
(
    `id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `price` DECIMAL(10,2) NOT NULL,
    `productID` INT NOT NULL,
    `amount` INT NOT NULL,
    `orderID` INT NOT NULL,
    FOREIGN KEY (productID) REFERENCES PRODUCT (productID),
    FOREIGN KEY (orderID) REFERENCES `ORDER` (orderID)
);

CREATE TABLE CATEGORY
(
    `categoryID` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `name` VARCHAR(50) NOT NULL,
    `description` TEXT
);

CREATE TABLE PRODUCTHASCATEGORY
(
    `id` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    productID INT NOT NULL,
    categoryID INT NOT NULL,
    FOREIGN KEY (productID) REFERENCES PRODUCT(productID),
    FOREIGN KEY (categoryID) REFERENCES CATEGORY(categoryID)
);

CREATE TABLE RATING
(
    `ratingID` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    productID INT NOT NULL,
    customerID INT NOT NULL,
    `ratingValue` INT NOT NULL,
    FOREIGN KEY (productID) REFERENCES PRODUCT (productID),
    FOREIGN KEY (customerID) REFERENCES CUSTOMER (customerID)
);

CREATE TABLE COMPANYDATA
(
    `ID` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `companyDescription` TEXT,
    `adress` VARCHAR(255),
    `phone` INT,
    `email` VARCHAR(255)
);

CREATE TABLE WORKDAYS 
(
    `ID` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    companyID INT NOT NULL,
    `startingHour` DATETIME,
    `closingHour` DATETIME,
    `openDay` VARCHAR(255),
    FOREIGN KEY (`companyID`) REFERENCES COMPANYDATA (ID)
);

CREATE TABLE NEWS
(
    `ID` INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `content` TEXT,
    `date` DATETIME
);

